TENANT_ID = "f73a06e7-4ed5-443b-b33c-3f6cd3b6ee9a"
CLIENT_ID = "774c15c8-b0ae-4d4d-ab35-05479ce84c94"
CLIENT_SECRET = "gnU8Q~DtHyDlc8yybbKVHzWG.chwQ8xHrYEijbym"

SP_HOSTNAME = "gestionintelcom.sharepoint.com"
SP_SITE_PATH = "/sites/Optimisation243"
SP_EXCEL_PATH = "/General/route_optimization_feedback.xlsx"
